### ISSUE TITLE
DO NOT CLOSE: PROJECT REQUIREMENTS CHECKLIST

### ISSUE THREAD

**Issue by EmilyNecciai** [EmilyNecciai/quizam#27]
# Project Requirements
- [x] Use Node.js and Express.js to create a RESTful API.
- [x] Use Handlebars.js as the templating engine.
- [x] Use MySQL and the Sequelize ORM for the database.
- [x] Have both GET and POST routes for retrieving and adding new data.
- [ ] Be deployed using Heroku (with data).
- [ ] Use at least one new library, package, or technology that we haven't discussed.
- [ ] Have a polished UI.
- [ ] Be responsive.
- [x] Be interactive (i.e., accept and respond to user input).
- [x] Have a folder structure that meets the MVC paradigm.
- [ ] Include authentication (express-session and cookies).
- [ ] Protect API keys and sensitive information with environment variables.
- [ ] Have a clean repository that meets quality coding standards (file structure, naming conventions, best practices for class/id naming conventions, indentation, quality comments, etc.).
- [x] #29
- [x] #28

# Presentation Requirements
You and your group will give a 10-minute presentation on your project, with about 7 minutes devoted to the presentation itself, followed by a 3-minute Question & Answer session. Use this Project Presentation Template (Links to an external site.) to address the following:

- [ ] Elevator pitch: A one-minute description of your application.
- [ ] Concept: What is your user story? What was your motivation for development?
- [ ] Process: What were the technologies used? How were tasks and roles broken down and assigned? What challenges did you encounter? What were your successes?
- [ ] Demo: Show your stuff!
- [ ] Directions for future development.
- [ ] Links to the deployed application and the GitHub repository. 

# Grading Requirements
This project is graded based on the following criteria:

## Technical Acceptance Criteria: 25%
Satisfies the following code requirements:

- [x] Application uses a Node and Express back end and uses both GET and POST routes for retrieving and adding new data.
- [x] Application has a folder structure that meets the MVC paradigm and uses Handlebars.js as the template engine.
- [x] Application is backed by a MySQL database with a Sequelize ORM and protects API keys and sensitive information with environment variables.
- [ ] Application includes user authentication (express-session and cookies).
- [x] Application uses at least one new library, package, or technology not covered in class.

## Concept 10%
- [x] Application should be a unique and novel idea.
- [x] Your group should clearly and concisely articulate your project idea.

## Deployment: 20%
- [ ] Application deployed at live URL on Heroku and loads with no errors.
- [ ] Application GitHub URL submitted.
- [ ] Portfolio at live URL submitted, featuring project.

## Repository Quality: 10%
- [x] Repository has a unique name.
- [x] Repository follows best practices for file structure and naming conventions.
- [x] Repository follows best practices for class/id naming conventions, indentation, quality comments, etc.
- [x] Repository contains multiple descriptive commit messages.
- [ ] Repository contains a quality README file with description, screenshot, and link to deployed application.

## Application Quality: 15%
- [ ] Application user experience is intuitive and easy to navigate.
- [ ] Application user interface style is clean and polished.
- [ ] Application is responsive.

## Presentation 10%
- [ ] Your group should present using Powerpoint or a similar presentation software.
- [ ] Every group member should speak during the presentation.
- [ ] Your presentation should follow the Project Presentation Template (Links to an external site.)

## Collaboration 10%
- [ ] There are no major disparities in the number of GitHub contributions between group members.
